development:
  adapter: postgresql
  encoding: unicode
  database: nomtracker_development
  pool: 5
  username: nomtracker
  password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning


test: &test
  adapter: postgresql
  encoding: unicode
  database: nomtracker_test
  pool: 5
  username: nomtracker
  password:

cucumber:
  <<: *test

production:
  adapter: postgresql
  uri: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  pool: 5
